-- AlterTable
ALTER TABLE "TimeSheetEntry" ADD COLUMN IF NOT EXISTS "effectiveMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TimeSheetEntry" ADD COLUMN IF NOT EXISTS "exclusiveMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TimeSheetEntry" ADD COLUMN IF NOT EXISTS "sharedMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TimeSheetEntry" ADD COLUMN IF NOT EXISTS "hasSharedMinutes" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TimeSheetEntry" ADD COLUMN IF NOT EXISTS "sharedConflictSnapshot" JSONB;
ALTER TABLE "TimeSheetEntry" ADD COLUMN IF NOT EXISTS "overlapGroupId" TEXT;
